name: rainbow_dqn
channels:
  - defaults
dependencies:
  - python=3.8
  - atari_py=0.2.6
  - gym=0.18.0
  - gym-atari=0.18.0
  - pytorch=1.4.0
  - tensorboardx=2.1
  - torchaudio=0.4.0
  - torchvision=0.5.0
